### ISSUE TITLE
accidental-hover issue

### ISSUE THREAD

**Issue by pink-eye** [yuschick/stylelint-plugin-defensive-css#11]
**Describe the bug**
When I define `accidental-hover` in `rules` I get error. When I remove it everything is fine.

**Expected behavior**
No output errors.

**Screenshots**
error with `accidental-hover: true`
<img width="1254" alt="screenshot" src="https://github.com/yuschick/stylelint-plugin-defensive-css/assets/62290775/8e006480-5555-40d2-be0e-b4b7df60bbf4">

output without `accidental-hover: true`
<img width="870" alt="screenshot" src="https://github.com/yuschick/stylelint-plugin-defensive-css/assets/62290775/3e7bc78c-c862-41cc-8670-bd61651c116f">

scripts in `package.json`
<img width="579" alt="screenshot" src="https://github.com/yuschick/stylelint-plugin-defensive-css/assets/62290775/20e152f8-9221-4aa5-b90c-8ef2901fa5f4">

**Additional context**
I use `stylelint` with `styled-components`, `stylelint-config-idiomatic-order`

`.stylelintrc`
```
{
	"extends": "stylelint-config-idiomatic-order",
	"customSyntax": "postcss-styled-syntax",
	"plugins": ["stylelint-plugin-defensive-css"],
	"rules": {
		"declaration-empty-line-before": [
			"always",
			{
				"ignore": [
					"after-comment",
					"after-declaration",
					"first-nested",
					"inside-single-line-block"
				]
			}
		],
		"plugin/use-defensive-css": [
			true,
			{
				"background-repeat": true,
				"custom-property-fallbacks": false,
				"flex-wrapping": true,
				"vendor-prefix-grouping": false,
				"accidental-hover": true,
				"scroll-chaining": true
			}
		]
	}
}
```

**Comment by yuschick** [comment]
Oh, interesting. I will look at this.

**Comment by pink-eye** [comment]
It works good now
Thanks!
