### ISSUE TITLE
Reports `( hover: hover )` as invalid

### ISSUE THREAD

**Issue by crstauf** [yuschick/stylelint-plugin-defensive-css#18]
**Describe the bug**
Does not accept `( hover: hover )`. Removing spaces resolves: `(hover: hover)`.

**To Reproduce**
1. Wrap style in `@media ( hover: hover ) {`
2. Run Stylelint: notice error
3. Change to `@media (hover: hover) {`
4. Run Stylelint: notice no error

**Expected behavior**
Be opinionated about the rule, and agnostic about coding styles.

**Screenshots**
<img width="515" alt="2023-10-16T132824" src="https://github.com/yuschick/stylelint-plugin-defensive-css/assets/4573033/57752387-4560-458b-81d9-f5638c450a44">
![2023-10-16T132626](https://github.com/yuschick/stylelint-plugin-defensive-css/assets/4573033/dee87b5d-09ac-4bdc-aaa0-a231d4a8e757)

**Desktop (please complete the following information):**
 - macOS
 - NA
 - NA

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**
None

**Comment by yuschick** [comment]
Thank you for reporting this. I'll take a look 👍

**Comment by yuschick** [comment]
This has been fixed in 0.9.2.

Thanks again for catching this one. Very helpful.
