### ISSUE TITLE
Include default value for `flex-wrap`

### ISSUE THREAD

**Issue by crstauf** [yuschick/stylelint-plugin-defensive-css#20]
Is there a way I can adjust the error message (per project) so that the default value for `flex-wrap` is included? I expect that junior devs on my team will see the error, and add `flex-wrap: wrap` without thinking, just to resolve the error.

If not, I may have to run without the rule in place, to prevent other problems.

**Comment by yuschick** [comment]
There's no support at this time for custom messaging. But I am happy to take suggestions on the message that would be more clear. I agree, it could mention the default `nowrap` and needing to explicitly define that if that's what is intended.

**Comment by yuschick** [comment]
I did a pass on all the error messages in #23. You can see the specific `flex-wrapping` error update [here](https://github.com/yuschick/stylelint-plugin-defensive-css/pull/23/files#diff-3bc5c69c1a983cc6b586e2390b20d8a2b147d74f4faf5ce3540a1fc5c7934c4bR17).
