### ISSUE TITLE
add support to stylelint 16 bro

### ISSUE THREAD

**Issue by ghost** [yuschick/stylelint-plugin-defensive-css#24]
Please support stylelint 16.0.0, the big one

Now the code is in ESM instead of CommonJS 

Very good

Stylelint team published docs to know how to migrate with ease.

No need to keep support to commons from now on.

Style lint 16 is not allowed in your package.json. remove this restriction to

**Comment by yuschick** [comment]
This update is on my radar. I'll get this updated 👍

**Comment by yuschick** [comment]
Looks like there is a limitation on the `jest-preset-stylelin` side. I can't get my tests to pass until they also support Stylelint 16. There is an open PR to support this already, so hopefully it'll happen soon. Once I am able to ensure my tests pass in both 15 and 16 environments, I will release support for this.

https://github.com/stylelint/jest-preset-stylelint/pull/87

**Comment by ximex** [comment]
the mentioned PR is now merged and a new version released

**Comment by yuschick** [comment]
🚀 Just published version 1.0.0 which now has support for Stylelint 16.
