### ISSUE TITLE
Adjust detection to ignore `:hover` within `:not()`

### ISSUE THREAD

**Issue by crstauf** [yuschick/stylelint-plugin-defensive-css#30]
**Describe the bug**
Using `:hover` within a `:not()` causes an error when there shouldn't be one.

**To Reproduce**
1. `.button:not( :hover ) {}`
2. Run Stylelint

**Expected behavior**
No error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: NA
 - Version: 14.2

**Comment by yuschick** [comment]
Ohh, this is an awesome catch. I'll get this updated ASAP. Thanks for reporting 🙏

**Comment by yuschick** [comment]
I just published version `1.0.1` which includes a fix for this false positive. Thanks again for reporting this 👏

**Comment by crstauf** [comment]
Confirmed: thanks!
