### ISSUE TITLE
vendor-prefix-grouping also reports pseudo-elements in CSS

### ISSUE THREAD

**Issue by aakashgill** [yuschick/stylelint-plugin-defensive-css#4]
Hi
I tried this plugin with vendor-prefix-grouping rule, but it turns out it's giving warning even for pseudo-elements in CSS.
Shouldn't it only report where vendor-prefixes are being used?

Attaching screenshots:

<img width="617" alt="new-styles-code" src="https://user-images.githubusercontent.com/8060831/232394384-a0728186-99a1-488b-ad1f-54ea175904c6.png">

<img width="679" alt="new-styles" src="https://user-images.githubusercontent.com/8060831/232394395-574710f8-0f3c-41fb-96e4-ed980febcf87.png">

Stylelintrc
![image](https://user-images.githubusercontent.com/8060831/232394660-253d6281-b458-4c7e-8f51-8c4dc754975d.png)

**Comment by yuschick** [comment]
Thanks for the screenshots. I will take a look at getting this fixed this week.

**Comment by yuschick** [comment]
Testing this now, and a selector with multiple pseudo-elements passes as expected.

What line is throwing the initial error in the file you showed, line 237? I wonder if there may be an issue stemming from there, because I don't see any linting underlines in the pseudo-selector screen shot.

**Comment by aakashgill** [comment]
Look at line number 634 in the screenshot.
I tried again with ::before, ::after
It still gives an error.

Did you try combining two pseudo elements with a comma and with no space between the two?

**Comment by yuschick** [comment]
I have added a couple tests and they are passing as expected.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/563226/233764259-0fe1cdbd-db21-4b8d-8d43-19a8b8fccbf0.png">

Since I cannot recreate an issue here, I would need a sample repo with the error happening. I would take a look around line 237 to see if there's an issue stemming from there, but hard to say what it could be at this point.

**Comment by aakashgill** [comment]
I replicated the error in this sample repo https://github.com/aakashgill/stylelint-plugin-defensive-css/
I'm still getting the error in this. Still not sure what I'm doing wrong.

![image](https://user-images.githubusercontent.com/8060831/233797628-9cbae658-b942-4b2a-81ed-846c17e51369.png)

**Comment by yuschick** [comment]
Thanks for the repo. It looks like the RegEx was matching `-type-`. But I've got an update coming shortly.

Appreciate the help in catchin this 👍

**Comment by yuschick** [comment]
This has been closed in #5 and released in version `0.2.0`.
